const puppeteer = require('puppeteer');

/**
 * Generates an HTML Table string for rendering.
 */
function generateHTMLTable(table) {
    const headers = table.headers.map(h => `<th>${h}</th>`).join('');
    const rows = table.rows.map(row =>
        `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`
    ).join('');

    return `
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h2 { color: #333; text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; color: #333; }
            tr:nth-child(even) { background-color: #f9f9f9; }
        </style>
    </head>
    <body>
        <h2>${table.title || 'Data Export'}</h2>
        <table>
            <thead><tr>${headers}</tr></thead>
            <tbody>${rows}</tbody>
        </table>
        <div style="margin-top: 20px; text-align: right; color: #777; font-size: 12px;">Generated by AI Assistant</div>
    </body>
    </html>
    `;
}

/**
 * Determines format and generates media buffer.
 * Rules:
 * - Columns <= 5 AND Rows <= 10 -> IMAGE (PNG)
 * - Else -> PDF (Landscape A4)
 */
async function generateTableMedia(table) {
    const colCount = table.headers.length;
    const rowCount = table.rows.length;
    const isSmallData = colCount <= 5 && rowCount <= 10;

    const htmlContent = generateHTMLTable(table);

    let browser;
    try {
        const puppeteerOptions = {
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        };

        if (process.env.PUPPETEER_EXECUTABLE_PATH) {
            puppeteerOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH;
        }

        browser = await puppeteer.launch(puppeteerOptions);
        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

        if (isSmallData) {
            // Generate Image
            // Set viewport to fit table comfortably
            await page.setViewport({ width: 800, height: 600, deviceScaleFactor: 2 });
            const element = await page.$('table'); // Focus on table or body

            // Screenshot full page or element (Element is better for cleanliness)
            const buffer = await element ? await element.screenshot({ type: 'png' }) : await page.screenshot({ fullPage: true });

            await browser.close();
            return {
                type: 'image',
                buffer: buffer,
                filename: 'table_view.png',
                mime: 'image/png',
                message: "Here is the data visualization:"
            };
        } else {
            // Generate PDF
            const buffer = await page.pdf({
                format: 'A4',
                landscape: true,
                printBackground: true,
                margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
            });

            await browser.close();
            return {
                type: 'pdf',
                buffer: buffer,
                filename: 'report.pdf',
                mime: 'application/pdf',
                message: `The table contains ${colCount} columns, which is not readable as an image on WhatsApp.\n📄 Download the full table as a PDF below.`
            };
        }
    } catch (error) {
        if (browser) await browser.close();
        console.error("Layout Generation Failed:", error);
        throw error;
    }
}

module.exports = { generateTableMedia };
